version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/lax/api/v2/package
  api_key:
    secure: OPFyWrslHKIkx8D7wRSY0Ws9o3ZvXOrtc4wabVsM8Fjlnjy80inJ4U6zf8KzSuXc
  skip_symbols: true
  on:
    branch: master
notifications:
 - provider: Slack
   auth_token:
     secure: uU+k+/TM+wxHhImZwtwluLeGiKOBQ6D6q8VlZw/TVYrdUyB9QjzyXiXCCvR17GJpdscX/I3QCRGVmzSG+arLePg+yKm3mTSAEzYlxBorguQ=
   on_build_success: true
   on_build_failure: true
   on_build_status_changed: true
